# Generated by Django 3.2 on 2021-05-08 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('tag_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cow_profile_pic', models.ImageField(null=True, upload_to='uploads/')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('date_of_entry', models.DateField(null=True)),
                ('no_of_children', models.PositiveIntegerField(null=True)),
                ('how_cattle_obtained', models.CharField(max_length=50, null=True)),
                ('is_alive', models.BooleanField(default=True)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cattlemapp.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cattle_name', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('phone_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('cattle_id', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='cattlemapp.cattle')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cattle_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True)),
                ('added_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattlemapp.animal')),
                ('cattle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cattlemapp.cattle')),
            ],
        ),
    ]
