# Generated by Django 3.2 on 2021-05-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattlemapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='breed',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
